title: Pedro H. S. Coutinho
logo: "assets/img/logo.jpg" # your photo (or logo) here

author:
email: 
twitter_username: coutinhopedroh
github_username: phcoutinho
description: Ms.C. in Electrical Engineering

theme: minima
