title: Pedro H. S. Coutinho
logo: "assets/img/eu.jpg" # your photo (or logo) here

author:
email: 
twitter_username: coutinhopedroh
github_username: phcoutinho
description: Ms.C. in Electrical Engineering

theme: jekyll-theme-minimal
