title: Pedro H. S. Coutinho
logo: "/images/logo.png?raw=true" # your photo (or logo) here

author:
email: 
twitter_username: coutinhopedroh
github_username: phcoutinho
description:

theme: jekyll-theme-minimal
